from __future__ import annotations


AM_EXTRACTION_SCHEMA: dict[str, object] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "records": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "source_id": {"type": ["string", "null"]},
                    "source_name": {"type": ["string", "null"]},
                    "doi": {"type": ["string", "null"]},
                    "record_id": {"type": ["string", "null"]},
                    "alloy": {"type": ["string", "null"]},
                    "alloy_family": {"type": ["string", "null"]},
                    "am_process": {"type": ["string", "null"]},
                    "laser_power_W": {"type": ["number", "null"]},
                    "scan_speed_mm_s": {"type": ["number", "null"]},
                    "hatch_spacing_um": {"type": ["number", "null"]},
                    "layer_thickness_um": {"type": ["number", "null"]},
                    "ved_J_mm3": {"type": ["number", "null"]},
                    "build_orientation": {"type": ["string", "null"]},
                    "surface_condition": {"type": ["string", "null"]},
                    "heat_treatment": {"type": ["string", "null"]},
                    "defect_type": {"type": ["string", "null"]},
                    "porosity_percent": {"type": ["number", "null"]},
                    "relative_density_percent": {"type": ["number", "null"]},
                    "test_type": {"type": ["string", "null"]},
                    "yield_strength_MPa": {"type": ["number", "null"]},
                    "uts_MPa": {"type": ["number", "null"]},
                    "elongation_percent": {"type": ["number", "null"]},
                    "fatigue_life_cycles": {"type": ["number", "null"]},
                    "stress_amplitude_MPa": {"type": ["number", "null"]},
                    "r_ratio": {"type": ["number", "null"]},
                    "runout": {"type": ["boolean", "null"]},
                    "failure_mode": {"type": ["string", "null"]},
                    "evidence_text": {"type": ["string", "null"]},
                    "extraction_confidence": {"type": "number"},
                    "needs_human_check": {"type": "boolean"},
                },
                "required": [
                    "source_id",
                    "source_name",
                    "doi",
                    "record_id",
                    "alloy",
                    "alloy_family",
                    "am_process",
                    "laser_power_W",
                    "scan_speed_mm_s",
                    "hatch_spacing_um",
                    "layer_thickness_um",
                    "ved_J_mm3",
                    "build_orientation",
                    "surface_condition",
                    "heat_treatment",
                    "defect_type",
                    "porosity_percent",
                    "relative_density_percent",
                    "test_type",
                    "yield_strength_MPa",
                    "uts_MPa",
                    "elongation_percent",
                    "fatigue_life_cycles",
                    "stress_amplitude_MPa",
                    "r_ratio",
                    "runout",
                    "failure_mode",
                    "evidence_text",
                    "extraction_confidence",
                    "needs_human_check",
                ],
            },
        }
    },
    "required": ["records"],
}